version: '3.8'

services:
  virginity-bot-server:
    build:
      context: './'
      dockerfile: './Dockerfile'
    ports:
      - '3000:3000'
    env_file: '.env'
    networks:
      - 'virgin-net'
    # depends_on:
    #   - virginity-bot-db
  # virginity-bot-db:
  #   image: postgres:14
  #   ports:
  #     - '5432:5432'
  #   env_file: virginity-bot.env
  #   networks:
  #     - virgin-net

networks:
  virgin-net:
