version: '3.8'

services:
  server:
    build:
      context: './'
      dockerfile: './Dockerfile.dev'
    env_file: '.env'
    environment:
      DATABASE_URL: 'postgres://postgres:password@virginity-bot-db/virginity-bot=value'
    volumes:
      - './:/home/vbot/app'
    networks:
      - 'virgin-net'
    depends_on:
      - 'db'
      - 'object-storage'
  db:
    image: 'docker.io/library/postgres:15'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'virginity-bot'
    volumes:
      - './files/db:/var/lib/postgresql/data'
    networks:
      - 'virgin-net'
  object-storage:
    image: 'quay.io/minio/minio:latest'
    command: 'server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: 'admin'
      MINIO_ROOT_PASSWORD: 'supersecret'
    volumes:
      - './files/object-storage:/data'
    networks:
      - 'virgin-net'

networks:
  virgin-net:
