name: 'Build & Publish Container images'

on:
  push:
    branches:
      - 'main'
      - 'master'

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Repository 🛎️'
        uses: 'actions/checkout@v3'
      - name: 'Use Node.js 📗'
        uses: 'actions/setup-node@v3'
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: 'Install packages 📥'
        run: 'npm install'

      - name: 'Build 🏗'
        run: 'NODE_ENV=production npm run build'

      - name: 'Cache build 🧩'
        uses: 'dudeofawesome/cache-build-artifact@v1'
        with:
          archive-name: 'build'

  lint:
    needs: 'build'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Get cached build 🧩'
        uses: 'dudeofawesome/retrieve-build-artifact@v1'
        with:
          archive-name: 'build'
      - name: 'Use Node.js 📗'
        uses: 'actions/setup-node@v3'
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: 'Lint 🚨'
        run: 'npm run lint'

  test:
    needs: 'build'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Get cached build 🧩'
        uses: 'dudeofawesome/retrieve-build-artifact@v1'
        with:
          archive-name: 'build'
      - name: 'Use Node.js 📗'
        uses: 'actions/setup-node@v3'
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: 'Test 🧪'
        run: 'npm run test'

  build-container:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Repository 🛎️'
        uses: 'actions/checkout@v3'
      - uses: 'docker/setup-buildx-action@v2'

      - name: 'Get node version 📗'
        id: 'node-version'
        run: |
          echo "node_version=$(cat '.nvmrc')" >> "$GITHUB_OUTPUT"
      - name: 'Get image tag names 🏷️'
        id: 'tag-image'
        run: |
          REPO=ghcr.io/$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] || [ "$VERSION" == "master" ] && VERSION=latest

          echo "image_tag=$REPO/bot:$VERSION" >> "$GITHUB_OUTPUT"

      - name: 'Build container 🐳'
        uses: 'docker/build-push-action@v3'
        with:
          file: 'Dockerfile'
          build-args: 'NODE_VERSION=${{ steps.node-version.outputs.node_version }}'
          tags: 'bot,${{ steps.tag-image.outputs.image_tag }}'
          cache-from: 'type=gha'
          cache-to: 'type=gha,mode=max'

    outputs:
      node_version: '${{ steps.node-version.outputs.node_version }}'
      image_tag: '${{ steps.tag-image.outputs.image_tag }}'

  publish:
    needs:
      - 'build-container'
      - 'lint'
      - 'test'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      packages: 'write'
    steps:
      - name: 'Checkout Repository 🛎️'
        uses: 'actions/checkout@v3'
      - uses: 'docker/setup-buildx-action@v2'
      - name: 'Login to GitHub Container Registry 🔑'
        uses: 'docker/login-action@v2'
        with:
          registry: 'ghcr.io'
          username: '${{ github.repository_owner }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'Publish to Registry 💨'
        uses: 'docker/build-push-action@v3'
        with:
          build-args: 'NODE_VERSION=${{ needs.build-container.outputs.node_version }}'
          push: true
          tags: '${{ needs.build-container.outputs.image_tag }}'
          cache-from: 'type=gha'
